apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: exam
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/student_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: "12345678"
