apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: exam
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 for "postgres"
  POSTGRES_PASSWORD: MTIzNDU2Nzg=  # base64 for "12345678"
  POSTGRES_DB: c3R1ZGVudF9kYg==  # base64 for "student_db"
