apiVersion: v1
kind: ResourceQuota
metadata:
  name: exam-quota
  namespace: exam
spec:
  hard:
    requests.cpu: "2"      # Total CPU requested by all pods must not exceed 2 cores
    requests.memory: "4Gi" # Total memory requested by all pods must not exceed 4Gi
    limits.cpu: "4"        # Total CPU limit across all pods must not exceed 4 cores
    limits.memory: "8Gi"   # Total memory limit across all pods must not exceed 8Gi
